  #####
  #####  RCV1: Supervised training using three types of tv-embedding
  #####
  #####  Step 1. Generate input files.
  #####  Step 2. Training. 
  #####
  #####  NOTE1: To run this script, download unlab_data.tar.gz and decompress it at test/, 
  #####         so that the directory test/unlab_data will be created. 
  #####
  #####  NOTE2: For your convenience, the files of the results of tv-embedding 
  #####         learning (*.layer0) are provided.  They are endian sensitive 
  #####         and were generated with Little Endian (Intel convention). 
  #####         If they are not usable in your system, you need to generate them 
  #####         in your system using the provided scripts (see the comments 
  #####         on s_fn0, s_fn1, and s_fn2 below) and set sdir=output below.  
  #####

  gpu=-1          # <= Change this to, e.g., "gpu=0" to use a specific GPU. 
  dim=100         # <= Change this to change dimensionality of tv-embedding. 
  sdir=unlab_data # <= Change this to the directory where tv-embedding files are. 
                  # <=   Provided at unlab_data/ (unlab_data.tar.gz). 
#  sdir=output    # <=   output/ if generated by semisup-rcv1-{unsup|unsup3|parsup}-tv.sh. 
  rcv1dir=../rcv1_data # <= Change this to the directory where RCV1 labeled data is. 

  prep=../bin/prepText
  cnet=../bin/conText

  options="LowerCase UTF8"
  txt_ext=.txt.tok

  z=d # to avoid name conflict with other scripts

  pch_sz=20
  s_fn0=${sdir}/rcv1-uns-p${pch_sz}.dim${dim}.ite10.layer0     # generated by semisup-rcv1-unsup-tv.sh
  s_fn1=${sdir}/rcv1-parsup-p20p${pch_sz}.dim${dim}.ite10.layer0  # generated by semisup-rcv1-parsup-tv.sh
  s_fn2=${sdir}/rcv1-unsx3-p${pch_sz}.dim${dim}.ite10.layer0   # generated by semisup-rcv1-unsup3-tv.sh

  #---  Step 1. Generate input files. 
  xvoc1=data/rcv1${z}-1m-trn.vocab
  $cnet $gpu write_word_mapping layer0_fn=$s_fn0 word_map_fn=$xvoc1  # extract word mapping from the tv-embedding file. 

  xvoc3=data/rcv1${z}-trn-123gram.vocab  
  $cnet $gpu write_word_mapping layer0_fn=$s_fn2 word_map_fn=$xvoc3  # extract word mapping from the tv-embedding file. 

  for set in train test; do 
    #---  dataset#0: (bow, same as semisup-rcv1-{unsup|unsup3|parsup}-tv.sh)
    rnm=data/rcv1${z}-1m-${set}-p${pch_sz}bow   
    $prep gen_regions Bow VariableStride WritePositions \
      region_fn_stem=$rnm input_fn=${rcv1dir}/rcv1-1m-${set} vocab_fn=$xvoc1 \
      $options text_fn_ext=$txt_ext label_fn_ext=.lvl2 \
      label_dic_fn=data/rcv1-lvl2.catdic \
      patch_size=$pch_sz patch_stride=2 padding=$((pch_sz-1))

    #---  dataset#1: (bag-of-1-3grams, same as semisup-rcv1-unsup3-tv.sh)
    pos_fn=${rnm}.pos  # make regions at the same locations as above. 
    rnm=data/rcv1${z}-1m-${set}-p${pch_sz}x3bow
    $prep gen_regions Bow input_pos_fn=$pos_fn \
      region_fn_stem=$rnm input_fn=${rcv1dir}/rcv1-1m-${set} vocab_fn=$xvoc3 \
      $options text_fn_ext=$txt_ext RegionOnly \
      patch_size=$pch_sz
  done


  #---  Step 2. Training. 
  gpumem=${gpu}:4  # pre-allocate 4GB GPU memory. 

  logfn=log_output/rcv1-semisup3-dim${dim}.log
  perffn=perf/rcv1-semisup3-dim${dim}.csv
  echo 
  echo Supervised training using 3 types of tv-embedding to produce additional input.   
  echo This takes a while.  See $logfn and $perffn for progress and see param/rcv1-semisup3.param for the rest of the parameters.
  $cnet $gpumem cnn 0side0_fn=$s_fn0 0side1_fn=$s_fn1 0side2_fn=$s_fn2 \
        trnname=rcv1${z}-1m-train-p${pch_sz} tstname=rcv1${z}-1m-test-p${pch_sz} \
        data_ext0=bow data_ext1=x3bow \
        0side0_dsno=0 0side1_dsno=0 0side2_dsno=1 \
        evaluation_fn=$perffn test_interval=25 LessVerbose \
        reg_L2=1e-4 step_size=0.25 \
        @param/rcv1-semisup3.param > $logfn


