  ####
  ####  Input: bag-of-ngram feature files and target files generated by 
  ####         for_baselines_imdb.sh, for_baselines_elec.sh, and for_baselines_rcv1.sh
  ####
  
  ./for_baselines_imdb.sh  # <= uncomment this if you haven't run it yet. 
  ./for_baselines_elec.sh  # <= uncomment this if you haven't run it yet. 
  ./for_baselines_rcv1.sh  # <= uncomment this if you haven't run it yet. 

  gpu=0  # <= change this to, e.g., "gpu=0" to use a specific GPU. 

  typ=bow3

  #---  IMDB: Training and test using GPU
  log_fn=log_output/imdb-densenn.log
  perf_fn=perf/imdb-densenn-perf.csv
  echo 
  echo IMDB: Training dense NN and testing ... 
  echo This takes a while.  See $log_fn and $perf_fn for progress and see param/densenn.param for the rest of the parameters. 
  ../bin/conText $gpu cnn \
         data_dir=data trnname=imdb_train-${typ} tstname=imdb_test-${typ} \
         nodes=50 reg_L2=1e-5 step_size=0.025 top_dropout=0.5 \
         LessVerbose test_interval=25 evaluation_fn=$perf_fn \
         @param/densenn.param > ${log_fn}

  #---  Elec: Training and test using GPU
  log_fn=log_output/elec-25k-densenn.log
  perf_fn=perf/elec-25k-densenn-perf.csv
  echo 
  echo Elec-25K: Training dense NN and testing ... 
  echo This takes a while.  See $log_fn and $perf_fn for progress and see param/densenn.param for the rest of the parameters. 
  ../bin/conText $gpu cnn \
         data_dir=data trnname=elec-25k_train-${typ} tstname=elec-25k_test-${typ} \
         nodes=50 reg_L2=1e-4 step_size=0.1 top_dropout=0.5 \
         LessVerbose test_interval=25 evaluation_fn=$perf_fn \
         @param/densenn.param > ${log_fn}

  #---  RCV1: Training and test using GPU
  log_fn=log_output/rcv1-1m-densenn.log
  perf_fn=perf/rcv1-1m-densenn-perf.csv
  echo 
  echo RCV1: Training dense NN and testing ... 
  echo This takes a while.  See $log_fn and $perf_fn for progress and see param/densenn.param for the rest of the parameters. 
  ../bin/conText $gpu cnn \
         data_dir=data trnname=rcv1-1m_train-${typ} tstname=rcv1-1m_test-${typ} \
         nodes=500 reg_L2=1e-5 step_size=0.5 \
         LessVerbose test_interval=25 evaluation_fn=$perf_fn \
         @param/densenn.param > ${log_fn}
