11,14d10
< 
< # modified by Chang, this flags need to be added of cudart, cublas,
< # these are the libs according to your installation of CUDA
< # To make it work well, add the correct lib names with corresponding version
17,20d12
< # modified by Chang, this needs to be chanaged according to your network structure
< # In K40 Telsa, we should use the compute_52, sm_52
< # otherwise it compiles well, but when running shell script it faile with "Get NULL String Cuda::getErrorString"
< # inclues, that's a strange error because of the CUDA installation.
22c14
<                 -gencode arch=compute_52,code=sm_52
---
>                 -gencode arch=compute_32,code=sm_32
70,88c62
< # add by Chang, for third parallel way of prepText, conText
< BIN_NAME3 = myText
< TARGET3 = $(BIN_DIR)/$(BIN_NAME3)
< CFLAGS3 = -Isrc/com -O2 -D__AZ_SMAT_SINGLE__
< 
< CPP_FILES3= 	\
< 	src/com/AzDmat.cpp \
< 	src/com/AzParam.cpp \
< 	src/com/AzSmat.cpp \
< 	src/com/AzStrPool.cpp \
< 	src/com/AzTools.cpp \
< 	src/com/AzTextMat.cpp \
< 	src/com/AzUtil.cpp \
< 	src/data/AzPrepText.cpp \
< 	src/data/AzTools_text.cpp \
< 	src/cnet/AzpCNet3_multi.cpp \
< 	src/cnet/AzpCNet3_multi_side.cpp \
< 
< all: $(TARGET1) $(TARGET2) $(TARGET3)
---
> all: $(TARGET1) $(TARGET2)
98,102d71
< # add myText for generating the preprocessing tokens and conText for training/testing
< ${TARGET3}:
< 	/bin/rm -f $(TARGET3)
< 	g++ -g $(CPP_FILES3) $(CFLAGS3) -o $(TARGET3)
< 
106c75
< 	/bin/rm -f $(TARGET3) # remember to free then
---
> 
