  ####  Input: token file (one review per line; tokens are delimited by white space) 
  ####         label file (one label per line)
  ####  These input files were generated by prep_imdb.sh and included in the package. 
  ####  To find the order of the data points, see prep_imdb.sh and the files at lst/.  

  gpu=-1  # <= change this to, e.g., "gpu=0" to use a specific GPU. 
  mem=2   # pre-allocate 2GB device memory 
  gpumem=${gpu}:${mem}

  prep_exe=../bin/prepText
  cnn_exe=../bin/conText

  options="LowerCase UTF8"

  #---  Step 1. Generate vocabulary
  echo Generaing vocabulary from training data ... 

  max_num=30000
  vocab_fn=data/imdb_trn-${max_num}.vocab
  $prep_exe gen_vocab input_fn=data/imdb-train.txt.tok vocab_fn=$vocab_fn max_vocab_size=$max_num \
                            $options WriteCount

  #---  Step 2. Generate region files (data/*.xsmatvar) and target files (data/*.y) for training and testing CNN.  
  #     We generate region vectors of the convolution layer and write them to a file, instead of making them 
  #     on the fly during training/testing. 
  echo 
  echo Generating region files ... 
  
  pch_sz=4

  for set in train test; do 
    rnm=data/imdb_${set}-p${pch_sz}
    $prep_exe gen_regions \
      region_fn_stem=$rnm input_fn=data/imdb-${set} vocab_fn=$vocab_fn \
      $options text_fn_ext=.txt.tok label_fn_ext=.cat \
      label_dic_fn=data/imdb_cat.dic \
      patch_size=$pch_sz patch_stride=1 padding=$((pch_sz-1))
  done


  #---  Step 3. Training and test using GPU
  log_fn=log_output/imdb-seq.log
  perf_fn=perf/imdb-seq-perf.csv
  echo 
  echo Training CNN and testing ... 
  echo This takes a while.  See $log_fn and $perf_fn for progress and see param/seq-bow.param for the rest of the parameters. 
  nodes=1000  # number of neurons (weight vectors) in the convolution layer. 
  $cnn_exe $gpumem cnn \
         data_dir=data trnname=imdb_train-p${pch_sz} tstname=imdb_test-p${pch_sz} \
         reg_L2=1e-4 step_size=0.05 top_dropout=0.5 \
         nodes=$nodes resnorm_width=$nodes \
         pooling_type=Max num_pooling=1 \
         LessVerbose test_interval=25 evaluation_fn=$perf_fn \
         @param/seq-bow.param > ${log_fn}

